dbtProject: # Este é o nome do seu perfil, deve ser igual ao 'profile' em dbt_project.yml
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: password
      dbname: dblight
      schema: public
      threads: 4